### ISSUE TITLE
cannot find deploy_batch40.prototxt

### ISSUE THREAD

**Issue by chenfei-wu** [TingAnChien/san-vqa-tensorflow#4]
Hello, 
May I ask where is vgg19/deploy_batch40.prototxt?
How do you define it?

**Comment by gina9726** [comment]
We downloaded vgg19 deploy.prototxt and caffemodel [here](https://gist.github.com/ksimonyan/3785162f95cd2d5fee77).
We just adjust the batch size from 10 to 40 to accelerate feature extraction, but it depends on your GPU memory size. If you want to change your batch size, you can simply modify the deploy file, and specify it in "prepro_img.py".

**Comment by chenfei-wu** [comment]
I downloaded the prototxt file and changed input_dim to 40, it works. Thanks -:)
