### ISSUE TITLE
How to visualize visual attention

### ISSUE THREAD

**Issue by haibin894609937** [TingAnChien/san-vqa-tensorflow#5]
How to visualize visual attention

**Comment by haibin894609937** [comment]
@TingAnChien

**Comment by TingAnChien** [comment]
Hi, we upsample the attention map to the original image size, then apply gaussian filter on it.
You can see the function below for our implementation. 
https://github.com/TingAnChien/san-vqa-tensorflow/blob/5305bbf3ef6d7357d82e7b9cf394e107dedd3f79/demo/demo_att.py#L194

**Comment by haibin894609937** [comment]
Thanks for your advice
