### ISSUE TITLE
transpose error in get_data()

### ISSUE THREAD

**Issue by jingjojo** [TingAnChien/san-vqa-tensorflow#6]
Hello,

The transpose img_feature = np.transpose(img_feature,(0,2,3,1)) in image normalization in get_data() in san_lstm_att.py throws error showing "ValueError: axes don't match array"

The original shape of img_feature is (71338, 4096). Can you tell me how I can fix this?

**Comment by TingAnChien** [comment]
Hi, 
I think you use the `fc7` feature since the dimension is 4096, and I already change the code `prepro_img.py` to extract pool5 feature map as default. Then the expected shape of img_feature should be something like (xxx, 512, 7, 7). Thanks for mentioning that.

**Comment by jingjojo** [comment]
Thanks for your reply. But why is the dimension 512, 7, 7? And what is xxx. Could you please explain

**Comment by TingAnChien** [comment]
xxx is the number of the data you load, and for the dimension (512, 7 ,7), please refer to section 3.1 in the paper for more details.
