### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by NiteshMethani** [TingAnChien/san-vqa-tensorflow#7]
Hi,
Which tensorflow version are you using?

It gave me an error while testing.

The exact error is as follows:
NotFoundError (see above for traceback): Key multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint

Any advice on how to fix it?

**Comment by NiteshMethani** [comment]
I am unable to do testing.
Training worked fine. After that I commented out train() function and tried to run the same code for testing. It is unable to restore the model.

I got the following error on line number 408 in san_lstm_att.py file.
NotFoundError (see above for traceback): Key att1//image_att_W not found in checkpoint

Any advice?

**Comment by TingAnChien** [comment]
fix the bug by adding variable scope 'embed' in generator
